# **Tutorial 3**

In [1]:

# Task 1: Create a numpy array of size 2 x 2
import numpy as np

array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 Array:")
print(array_2x2)


2x2 Array:
[[1 2]
 [3 4]]


In [2]:

# Task 2: Create a random numpy array of size 3 x 4
random_3x4 = np.random.rand(3, 4)
print("Random 3x4 Array:")
print(random_3x4)


Random 3x4 Array:
[[0.42121907 0.12221845 0.05696236 0.98851681]
 [0.13423095 0.75025352 0.5547954  0.99771429]
 [0.26714896 0.70777422 0.42603281 0.19261423]]


In [3]:

# Task 3: Create numpy arrays of ones and zeroes
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))

print("Array of Ones:")
print(ones_array)
print("\nArray of Zeroes:")
print(zeros_array)


Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Array of Zeroes:
[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:

# Task 4: Create a random numpy array of size 6x3 and transpose it
rand_6x3 = np.random.randint(1, 10, (6, 3))
print("Original 6x3 Array:")
print(rand_6x3)

transposed = rand_6x3.T
print("\nTransposed Array (3x6):")
print(transposed)


Original 6x3 Array:
[[6 5 7]
 [8 6 9]
 [4 3 6]
 [9 7 4]
 [4 6 5]
 [1 4 4]]

Transposed Array (3x6):
[[6 8 4 9 4 1]
 [5 6 3 7 6 4]
 [7 9 6 4 5 4]]


In [5]:
# Task 5: Create two random numpy arrays of size n x p and p x m and compute the dot product
n, p, m = 2, 3, 4  # matrix dimensions
A = np.random.randint(1, 10, (n, p))
B = np.random.randint(1, 10, (p, m))

print("Matrix A (size n x p):")
print(A)
print("\nMatrix B (size p x m):")
print(B)

dot_product = np.dot(A, B)
print("\nDot Product Result (size n x m):")
print(dot_product)

Matrix A (size n x p):
[[3 8 7]
 [1 9 3]]

Matrix B (size p x m):
[[2 5 5 7]
 [7 1 9 7]
 [6 9 4 4]]

Dot Product Result (size n x m):
[[104  86 115 105]
 [ 83  41  98  82]]
